---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 3002
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  envFrom:
    - secret: {{secret}}
  redis:
    - instance: pagecache
      access: write
  accessPolicy:
    inbound:
      rules:
        - application: {{frontendApp}}
        - application: {{frontendFailover}}
    outbound:
      rules:
        - application: {{frontendApp}}
  replicas:
    min: 1
    max: 1
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}