---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  team: personbruker
  port: 3002
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  ingresses:
    - {{ingress}}
  env:
    - name: SERVICE_SECRET
      value: {{serviceSecret}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: '2'
      memory: 512Mi
    requests:
      memory: 256Mi
