---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: nav-enonicxp-frontend-revalidator-proxy
  namespace: {{namespace}}
  labels:
    team: personbruker
spec:
  image: {{image}}:{{version}}
  team: personbruker
  port: 3002
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  envFrom:
    - secret: {{secret}}
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: '2'
      memory: 512Mi
    requests:
      memory: 256Mi
