---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{appName}}
  namespace: navno
  labels:
    team: navno
spec:
  image: {{image}}
  port: 3002
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  env:
    - name: NPM_CONFIG_CACHE
      value: /tmp/npm-cache
  envFrom:
    - secret: {{secret}}
  valkey:
    - instance: pagecache
      access: write
  accessPolicy:
    inbound:
      rules:
        - application: {{frontendApp}}
          namespace: personbruker
        - application: {{frontendFailover}}
          namespace: personbruker
        - application: {{frontendApp}}
          namespace: navno
        - application: {{frontendFailover}}
          namespace: navno
    outbound:
      rules:
        - application: {{frontendApp}}
          namespace: personbruker
        - application: {{frontendApp}}
          namespace: navno
  replicas:
    min: 1
    max: 1
  resources:
  {{#with resources}}
    requests:
      cpu: {{requests.cpu}}
      memory: {{requests.memory}}
    limits:
      memory: {{limits.memory}}
  {{/with}}