name: Build and deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      cluster:
        required: true
        type: string
      vars_file:
        required: true
        type: string
      push_latest:
        required: false
        type: boolean
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  build-and-deploy:
    name: Build and deploy to nais k8s
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: ./.github/actions/build-and-deploy
        with:
          environment: ${{ inputs.environment }}
          cluster: ${{ inputs.cluster }}
          vars_file: ${{ inputs.vars_file }}
          push_latest: ${{ inputs.push_latest }}
        env:
          NAIS_MANAGEMENT_PROJECT_ID: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}