name: Build and deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      imagename:
        required: true
        type: string
      ingress:
        required: true
        type: string
      cluster:
        required: true
        type: string
      appName:
        required: true
        type: string
      frontendAppName:
        required: true
        type: string
    secrets:
      SERVICE_SECRET:
        required: true
      NAIS_DEPLOY_APIKEY:
        required: true

jobs:
  build-and-deploy:
    name: Build docker image and deploy to nais k8s
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      image: ghcr.io/${{ github.repository }}:${{ inputs.imagename }}-${{ github.sha }}
    outputs:
      image: ${{ env.image }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Define app environmment
        env:
          SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
        run: |
          cat > .env <<EOF
          SERVICE_SECRET=$SERVICE_SECRET
          EOF
      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        id: build_image
        run: |
          docker build -t ${{ env.image }} .
          docker push ${{ env.image }}
      - name: Set nais variables
        run: |
          cat > .nais/vars.yaml <<EOF
          appName: ${{ inputs.appName }}
          frontendAppName: ${{ inputs.frontendAppName }}
          image: ${{ env.image }}
          ingress: ${{ inputs.ingress }}
          EOF
      - uses: nais/deploy/actions/deploy@master
        env:
          CLUSTER: ${{ inputs.cluster }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/config-new.yaml
          VARS: .nais/vars.yaml
