name: Deploy to prod
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod-gcp
      imagename: prod-deploy
      ingress: https://nav-enonicxp-frontend-revalidator-proxy.intern.nav.no
      appName: nav-enonicxp-frontend-revalidator-proxy
      frontendAppName: nav-enonicxp-frontend
      cluster: prod-gcp
    secrets:
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
