name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: prod
      cluster: prod-gcp
      vars_file: vars-prod.yml
      push_latest: true
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
