name: Deploy to dev1
on:
  workflow_dispatch

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev-gcp:dev1
      imagename: dev1-deploy
      ingress: https://nav-enonicxp-frontend-revalidator-proxy-dev1.dev.nav.no
      appName: nav-enonicxp-frontend-revalidator-proxy-dev1
      frontendAppName: nav-enonicxp-frontend-dev1
      cluster: dev-gcp
    secrets:
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
