name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  build-and-deploy:
    if: github.event.release.target_commitish == 'master'
    uses: ./.github/workflows/build-and-deploy.yml
    permissions:
      contents: "read"
      id-token: "write"
    with:
      environment: prod
      cluster: prod-gcp
      vars_file: vars-prod.yml
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
  push-to-ghcr:
    uses: ./.github/workflows/push-to-ghcr.yml
    needs: build-and-deploy
    permissions:
      contents: "read"
      packages: "write"
    with:
      image: ${{ needs.build-and-deploy.outputs.image }}
